### ISSUE TITLE
Create 0.2 release a publish to https://spark-packages.org/ (or some other central place)

### ISSUE THREAD

**Issue by barrybecker4** [sramirez/spark-MDLP-discretization#21]
Currently the mast branch is building 0.2-SNAPSHOT. As soon as #14 is fixed, it might be a good idea to create the 0.2 release publish the package to https://spark-packages.org/ so it can get wider usage.

**Comment by sramirez** [comment]
Yes, of course. 

Let's wait and see if more changes come, let's say in a couple of weeks. If no more changes are introduced, I'll upload a new version to the spark-packages repository.

**Comment by barrybecker4** [comment]
sounds good.

**Comment by sramirez** [comment]
Some days ago I've uploaded a new version of DMDLP with all problems related to Spark 2.0 and metadata fixed. I'm gonna spend some time trying to fuse my approximate version and your exact but slower version. When I have something relevant, I'll let you know.

**Comment by barrybecker4** [comment]
cool. thanks.
