### ISSUE TITLE
Add some unit tests

### ISSUE THREAD

**Issue by barrybecker4** [sramirez/spark-MDLP-discretization#3]
It would be nice to add some unit tests that would prove that it works as expected and act as documentation by way of examples. I will try to add some and do a PR.

**Comment by barrybecker4** [comment]
I created a pull request: https://github.com/sramirez/spark-MDLP-discretization/pull/5

**Comment by sramirez** [comment]
I've just merged PR #5. Nice addition. 
maxBins bug is now fixed. I get erros in test 6, 7, 8, and 10. I've fixed test 2.
I think in 6,7,8 there is a problem with number precision.

I think I'll also include the unit test that I've been using in my experiments, which consist of data from the paper associated to this project.

**Comment by barrybecker4** [comment]
That would be great. Thanks.

**Comment by barrybecker4** [comment]
Initial unit tests have been added. We can always add more as needed. Current tests are all passing. I will close this.
